import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

export const viewport: Viewport = {
  // Tints the browser chrome (iOS Safari bars, Android status bar) to the
  // wave base color instead of leaving it to sample whatever sits at the
  // page edge.
  themeColor: "#F2EFE8",
};

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.infitra.fit";
// Umami analytics (cloud.umami.is) — cookieless, so no consent banner
// needed, and the free tier (100k events/mo) is far beyond pilot volume.
// Replaced Plausible before activation: Plausible turned out to be paid
// after a 30-day trial. Inert until NEXT_PUBLIC_UMAMI_WEBSITE_ID is set in
// the Vercel env, so this code ships now and goes live the moment the
// account exists. Swapping providers again is this block + lib/analytics.ts.
// Accept either the bare website UUID or a pasted <script> tag: Umami's UI
// hands you the whole snippet, and pasting that verbatim silently nests the
// tag inside data-website-id, so tracking looks configured but records
// nothing. Extract the first UUID and ignore the rest.
const UMAMI_WEBSITE_ID = (process.env.NEXT_PUBLIC_UMAMI_WEBSITE_ID ?? "")
  .match(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i)?.[0];
const UMAMI_SRC =
  process.env.NEXT_PUBLIC_UMAMI_SRC ?? "https://cloud.umami.is/script.js";
const DESCRIPTION =
  "Complementary experts, one live fitness experience. INFITRA provides the live rooms, the tribe space, the marketing page with checkout, the collaboration contract and the revenue splitting.";

export const metadata: Metadata = {
  // Resolves relative OG/Twitter image URLs (incl. the generated
  // /opengraph-image) to absolute ones; without it Next falls back to
  // localhost and social scrapers get a dead image.
  metadataBase: new URL(SITE_URL),
  title: "INFITRA · Live, co-created fitness experiences",
  description: DESCRIPTION,
  // The card itself is generated by app/opengraph-image.tsx — Next injects
  // og:image + dimensions automatically, so no images are listed here.
  openGraph: {
    type: "website",
    url: "/",
    siteName: "INFITRA",
    title: "INFITRA · Live, co-created fitness experiences",
    description: DESCRIPTION,
  },
  twitter: {
    card: "summary_large_image",
    title: "INFITRA · Live, co-created fitness experiences",
    description: DESCRIPTION,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full`}>
      <head>
        {/* General Sans — upright weights only. The INFITRA wordmark's
            italic look comes from the browser synthesising oblique from
            the upright bold; that's the characteristic thicker italic
            production has always rendered. Loading real italic variants
            replaces that with thinner real-italic glyphs, which loses
            the brand feel. Keep upright-only. */}
        <link
          rel="stylesheet"
          href="https://api.fontshare.com/v2/css?f[]=general-sans@200,300,400,500,600,700&display=swap"
        />
      </head>
      {/* no bg-surface here — the utility would override the #F2EFE8 canvas
          rule in globals.css with the grey surface token */}
      <body className="min-h-full flex flex-col antialiased text-on-surface">
        {children}
        {UMAMI_WEBSITE_ID && (
          <Script
            src={UMAMI_SRC}
            data-website-id={UMAMI_WEBSITE_ID}
            strategy="afterInteractive"
          />
        )}
      </body>
    </html>
  );
}
